name: loomi_flutter_chall
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  json_serializable: ^6.8.0
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  mobx: ^2.3.3+2
  mobx_codegen: ^2.6.1
  flutter_mobx: ^2.2.1+1
  get_it: ^7.6.7
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  rxdart: ^0.27.7
  flutter_hooks: ^0.20.5
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Epilogue
      fonts:
        - asset: assets/fonts/Epilogue-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Epilogue-VariableFont_wght.ttf

    - family: LoomiIcons
      fonts:
        - asset: assets/fonts/LoomiIcons.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
