// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgklVnGCs0OjMgvjGGKWfwvTc4rQpv7Pk',
    appId: '1:556432479913:web:d62e774d831e1008d53bb8',
    messagingSenderId: '556432479913',
    projectId: 'loomi-chall',
    authDomain: 'loomi-chall.firebaseapp.com',
    storageBucket: 'loomi-chall.appspot.com',
    measurementId: 'G-73QRNVWM8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMakt8_Xgm3WToF3twlV32RBNzJhH-H10',
    appId: '1:556432479913:android:5ac16253728dd10ad53bb8',
    messagingSenderId: '556432479913',
    projectId: 'loomi-chall',
    storageBucket: 'loomi-chall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjbgLM2_doJpWg51ApPkwnCbCA5W8U0Qo',
    appId: '1:556432479913:ios:9c55facb9839b1b2d53bb8',
    messagingSenderId: '556432479913',
    projectId: 'loomi-chall',
    storageBucket: 'loomi-chall.appspot.com',
    iosBundleId: 'com.example.loomiFlutterChall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjbgLM2_doJpWg51ApPkwnCbCA5W8U0Qo',
    appId: '1:556432479913:ios:9c55facb9839b1b2d53bb8',
    messagingSenderId: '556432479913',
    projectId: 'loomi-chall',
    storageBucket: 'loomi-chall.appspot.com',
    iosBundleId: 'com.example.loomiFlutterChall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgklVnGCs0OjMgvjGGKWfwvTc4rQpv7Pk',
    appId: '1:556432479913:web:8ba698509f3c237bd53bb8',
    messagingSenderId: '556432479913',
    projectId: 'loomi-chall',
    authDomain: 'loomi-chall.firebaseapp.com',
    storageBucket: 'loomi-chall.appspot.com',
    measurementId: 'G-1BJKV9PY06',
  );
}
